import type { Metadata } from "next";
import "./globals.css";
import GoogleAdsense from "@/components/google-ad-sense";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh_cn">
      <body>{children}</body>
      <GoogleAdsense pId={process.env.ADSENSE_PID || ""} />
    </html>
  );
}
