import type { Metadata } from "next";
import "./globals.css";
import GoogleAdsense from "@/components/google-ad-sense";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh_cn">
      <body>
        <Header />
        {children}
        <GoogleAdsense pId={process.env.ADSENSE_PID || ""} />
      </body>
    </html>
  );
}
