import type { Metadata } from "next";
import "../globals.css";
import GoogleAdsense from "@/components/google-ad-sense";
import Header from "@/components/header";
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <head>
        <GoogleAdsense pId={process.env.ADSENSE_PID || ""} />
      </head>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Header />
          {children}
          <Toaster />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
